name: snazy_optimizer
description: "A gaming performance optimizer for Android."
publish_to: 'none'

version: 1.0.10+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  battery_plus: ^5.0.3
  installed_apps: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
